language: node_js
sudo: false

node_js:
  - '6.10.2'

branches:
  only:
  - master

  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
    - MODE=lint
    - MODE=aot
    - MODE=closure-compiler
    - MODE=payload
    - MODE=e2e
    - MODE=saucelabs_required
    - MODE=browserstack_required

matrix:
  fast_finish: true
  allow_failures:
  - env: "MODE=saucelabs_optional"
  - env: "MODE=browserstack_optional"

install:
  - npm install

before_script:
  - mkdir -p $LOGS_DIR

script:
  - npm build -prod

cache:
  directories:
    - node_modules
    - $HOME/.pub-cache
